=== Tumbleweed103/ITMO.HTML_XML.Labs/XML/Lab02/lessons_DTD.dtd
<!ELEMENT lessons:Timetable (lessons:CourseName|lessons:DateBegin
                             |lessons:DateEnd|lessons:Hours
                             |lessons:Lecturer)+>
<!ATTLIST lessons:Timetable
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'>

<!ELEMENT lessons:CourseName (#PCDATA)>
<!ATTLIST lessons:CourseName
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'
  id CDATA #REQUIRED>

<!ELEMENT lessons:DateBegin (#PCDATA)>
<!ATTLIST lessons:DateBegin
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'>

<!ELEMENT lessons:DateEnd (#PCDATA)>
<!ATTLIST lessons:DateEnd
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'>

<!ELEMENT lessons:Hours (#PCDATA)>
<!ATTLIST lessons:Hours
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'>

<!ELEMENT lessons:Lecturer (#PCDATA)>
<!ATTLIST lessons:Lecturer
  xmlns:lessons CDATA #FIXED 'http://www.itmo.ru/xml/lessons'>

=== Tumbleweed103/ITMO.HTML_XML.Labs/XML/Lab02/lessons.xml
<?xml version = "1.0" encoding = "utf-8" ?>
<!DOCTYPE TimeTable SYSTEM "lessons_DTD.dtd">

<lessons:Timetable xmlns:lessons = "http://www.itmo.ru/xml/lessons">
	<lessons:CourseName id = "1">Технологии программирования</lessons:CourseName>
		<lessons:DateBegin>29.09.2020</lessons:DateBegin>
		<lessons:DateEnd>16.10.2020</lessons:DateEnd>
		<lessons:Lecturer>Осипов Н.А.</lessons:Lecturer>
		<lessons:Hours>50</lessons:Hours>
	<lessons:CourseName id = "2">Программирование на C#</lessons:CourseName>
		<lessons:DateBegin>19.10.2020</lessons:DateBegin>
		<lessons:DateEnd>06.11.2020</lessons:DateEnd>
		<lessons:Lecturer>Осипов Н.А.</lessons:Lecturer>
		<lessons:Hours>50</lessons:Hours>
	<lessons:CourseName id = "3">Введение в базы данных</lessons:CourseName>
		<lessons:DateBegin>09.11.2020</lessons:DateBegin>
		<lessons:DateEnd>20.11.2020</lessons:DateEnd>
		<lessons:Lecturer>Осетрова И.С.</lessons:Lecturer>
		<lessons:Hours>30</lessons:Hours>
	<lessons:CourseName id = "4">Разработка Windows-приложений на C#</lessons:CourseName>
		<lessons:DateBegin>23.11.2020</lessons:DateBegin>
		<lessons:DateEnd>11.12.2020</lessons:DateEnd>
		<lessons:Lecturer>Смольянинов А.В.</lessons:Lecturer>
		<lessons:Hours>50</lessons:Hours>
	<lessons:CourseName id = "5">Основы технологий разметки(HTML, XML)</lessons:CourseName>
		<lessons:DateBegin>14.12.2020</lessons:DateBegin>
		<lessons:DateEnd>18.12.2020</lessons:DateEnd>
		<lessons:Lecturer>Смольянинов А.В.</lessons:Lecturer>
		<lessons:Hours>20</lessons:Hours>
	<lessons:CourseName id = "6">Transact-SQL и Разработка Microsoft SQL Server</lessons:CourseName>
		<lessons:DateBegin>21.12.2020</lessons:DateBegin>
		<lessons:DateEnd>29.12.2020</lessons:DateEnd>
		<lessons:Lecturer>Ямщиков Д.В.</lessons:Lecturer>
		<lessons:Hours>25</lessons:Hours>
</lessons:Timetable>
